BEGIN TRANSACTION;
CREATE TABLE "player" ([_id] INTEGER PRIMARY KEY AUTOINCREMENT,
[pgroup] TEXT,
[name] TEXT,
[pnumber] TEXT,
[position] TEXT
);

INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('1','阪神タイガース','和田　豊','86','監督');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('2','阪神タイガース','渡辺　亮','12','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('3','阪神タイガース','榎田　大樹','13','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('4','阪神タイガース','能見　篤史','14','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('5','阪神タイガース','藤原　正典','15','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('6','阪神タイガース','安藤　優也','16','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('7','阪神タイガース','岩貞　祐太','17','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('8','阪神タイガース','藤浪　晋太郎','19','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('9','阪神タイガース','筒井　和也','20','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('10','阪神タイガース','岩田　稔','21','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('11','阪神タイガース','呉　昇桓','22','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('12','阪神タイガース','歳内　宏明','26','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('13','阪神タイガース','秋山　拓巳','27','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('14','阪神タイガース','福原　忍','28','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('15','阪神タイガース','小嶋　達也','29','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('16','阪神タイガース','久保田　智之','30','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('17','阪神タイガース','高宮　和也','34','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('18','阪神タイガース','田面　巧二郎','41','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('19','阪神タイガース','吉見　祐治','42','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('20','阪神タイガース','西村　憲','43','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('21','阪神タイガース','鶴　直人','46','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('22','阪神タイガース','山本　翔也','47','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('23','阪神タイガース','金田　和之','48','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('24','阪神タイガース','ランディ・メッセンジャー','54','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('25','阪神タイガース','松田　遼馬','56','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('26','阪神タイガース','岩本　輝','59','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('27','阪神タイガース','加藤　康介','63','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('28','阪神タイガース','白仁田　寛和','64','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('29','阪神タイガース','二神　一人','66','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('30','阪神タイガース','岩崎　優','67','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('31','阪神タイガース','伊藤　和雄','92','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('32','阪神タイガース','玉置　隆','97','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('33','阪神タイガース','日高　剛','37','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('34','阪神タイガース','小宮山　慎二','39','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('35','阪神タイガース','鶴岡　一成','40','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('36','阪神タイガース','梅野　隆太郎','44','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('37','阪神タイガース','清水　誉','45','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('38','阪神タイガース','今成　亮太','49','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('39','阪神タイガース','藤井　彰人','50','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('40','阪神タイガース','小豆畑　眞也','52','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('41','阪神タイガース','岡崎　太一','57','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('42','阪神タイガース','鳥谷　敬','1','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('43','阪神タイガース','北條　史也','2','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('44','阪神タイガース','関本　賢太郎','3','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('45','阪神タイガース','上本　博紀','4','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('46','阪神タイガース','マウロ・ゴメス','5','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('47','阪神タイガース','西岡　剛','7','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('48','阪神タイガース','新井　貴浩','25','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('49','阪神タイガース','新井　良太','32','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('50','阪神タイガース','西田　直斗','33','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('51','阪神タイガース','坂　克彦','35','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('52','阪神タイガース','黒瀬　春樹','38','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('53','阪神タイガース','陽川　尚将','55','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('54','阪神タイガース','荒木　郁也','58','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('55','阪神タイガース','森田　一成','69','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('56','阪神タイガース','柴田　講平','00','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('57','阪神タイガース','大和','0','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('58','阪神タイガース','福留　孝介','8','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('59','阪神タイガース','マット・マートン','9','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('60','阪神タイガース','横田　慎太郎','24','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('61','阪神タイガース','一二三　慎太','36','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('62','阪神タイガース','伊藤　隼太','51','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('63','阪神タイガース','中谷　将大','60','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('64','阪神タイガース','田上　健一','61','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('65','阪神タイガース','高山　久','62','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('66','阪神タイガース','緒方　凌介','65','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('67','阪神タイガース','俊介','68','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('68','阪神タイガース','狩野　恵輔','99','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('69','広島東洋カープ','野村　謙二郎','77','監督');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('70','広島東洋カープ','福井　優也','11','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('71','広島東洋カープ','九里　亜蓮','12','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('72','広島東洋カープ','大瀬良　大地','14','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('73','広島東洋カープ','今村　猛','16','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('74','広島東洋カープ','前田　健太','18','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('75','広島東洋カープ','野村　祐輔','19','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('76','広島東洋カープ','永川　勝浩','20','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('77','広島東洋カープ','篠田　純平','21','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('78','広島東洋カープ','中村　恭平','22','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('79','広島東洋カープ','横山　竜士','23','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('80','広島東洋カープ','河内　貴哉','24','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('81','広島東洋カープ','岩見　優輝','28','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('82','広島東洋カープ','江草　仁貴','29','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('83','広島東洋カープ','一岡　竜司','30','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('84','広島東洋カープ','中田　廉','34','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('85','広島東洋カープ','齊藤　悠葵','36','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('86','広島東洋カープ','梅津　智弘','39','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('87','広島東洋カープ','上野　弘文','41','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('88','広島東洋カープ','ブライアン・バリントン','42','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('89','広島東洋カープ','大島　崇行','46','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('90','広島東洋カープ','小野　淳平','47','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('91','広島東洋カープ','西原　圭大','48','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('92','広島東洋カープ','戸田　隆矢','53','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('93','広島東洋カープ','武内　久士','54','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('94','広島東洋カープ','中崎　翔太','56','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('95','広島東洋カープ','キャム・ミコライオ','57','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('96','広島東洋カープ','ザック・フィリップス','58','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('97','広島東洋カープ','今井　啓介','62','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('98','広島東洋カープ','久本　祐一','65','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('99','広島東洋カープ','中村　祐太','67','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('100','広島東洋カープ','池ノ内　亮介','68','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('101','広島東洋カープ','上村　和裕','27','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('102','広島東洋カープ','石原　慶幸','31','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('103','広島東洋カープ','白濱　裕太','32','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('104','広島東洋カープ','倉　義和','40','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('105','広島東洋カープ','磯村　嘉孝','61','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('106','広島東洋カープ','會澤　翼','64','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('107','広島東洋カープ','上本　崇司','0','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('108','広島東洋カープ','東出　輝裕','2','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('109','広島東洋カープ','小窪　哲也','4','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('110','広島東洋カープ','栗原　健太','5','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('111','広島東洋カープ','梵　英心','6','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('112','広島東洋カープ','堂林　翔太','7','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('113','広島東洋カープ','キラ・カアイフエ','13','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('114','広島東洋カープ','菊池　涼介','33','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('115','広島東洋カープ','松本　高明','45','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('116','広島東洋カープ','鈴木　誠也','51','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('117','広島東洋カープ','庄司　隼人','52','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('118','広島東洋カープ','ブラッド・エルドレッド','55','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('119','広島東洋カープ','美間　優槻','59','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('120','広島東洋カープ','安部　友裕','60','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('121','広島東洋カープ','田中　広輔','63','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('122','広島東洋カープ','木村　昇吾','66','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('123','広島東洋カープ','中東　直己','00','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('124','広島東洋カープ','丸　佳浩','9','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('125','広島東洋カープ','岩本　貴裕','10','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('126','広島東洋カープ','高橋　大樹','25','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('127','広島東洋カープ','廣瀬　純','26','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('128','広島東洋カープ','下水流　昂','35','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('129','広島東洋カープ','松山　竜平','37','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('130','広島東洋カープ','赤松　真人','38','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('131','広島東洋カープ','土生　翔平','43','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('132','広島東洋カープ','迎　祐一郎','44','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('133','広島東洋カープ','天谷　宗一郎','49','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('134','広島東洋カープ','鈴木　将光','50','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('135','広島東洋カープ','ライネル・ロサリオ','69','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('136','広島東洋カープ','中村　憲','99','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('137','中日ドラゴンズ','谷繁　元信','27','監督');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('138','中日ドラゴンズ','川上　憲伸','11','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('139','中日ドラゴンズ','田島　慎二','12','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('140','中日ドラゴンズ','岩瀬　仁紀','13','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('141','中日ドラゴンズ','朝倉　健太','14','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('142','中日ドラゴンズ','又吉　克樹','16','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('143','中日ドラゴンズ','雄太','17','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('144','中日ドラゴンズ','鈴木　翔太','18','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('145','中日ドラゴンズ','吉見　一起','19','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('146','中日ドラゴンズ','岡田　俊哉','21','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('147','中日ドラゴンズ','大野　雄大','22','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('148','中日ドラゴンズ','鈴木　義広','23','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('149','中日ドラゴンズ','福谷　浩司','24','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('150','中日ドラゴンズ','武藤　祐太','25','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('151','中日ドラゴンズ','山内　壮馬','26','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('152','中日ドラゴンズ','岩田　慎司','28','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('153','中日ドラゴンズ','山井　大介','29','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('154','中日ドラゴンズ','阿知羅　拓馬','30','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('155','中日ドラゴンズ','西川　健太郎','32','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('156','中日ドラゴンズ','祖父江　大輔','33','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('157','中日ドラゴンズ','山本昌','34','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('158','中日ドラゴンズ','辻　孟彦','35','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('159','中日ドラゴンズ','三瀬　幸司','39','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('160','中日ドラゴンズ','浅尾　拓也','41','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('161','中日ドラゴンズ','濱田　達郎','43','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('162','中日ドラゴンズ','ネルソン・パヤノ','47','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('163','中日ドラゴンズ','川崎　貴弘','51','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('164','中日ドラゴンズ','井上　公志','53','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('165','中日ドラゴンズ','小川　龍也','57','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('166','中日ドラゴンズ','矢地　健人','59','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('167','中日ドラゴンズ','若松　駿太','61','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('168','中日ドラゴンズ','小熊　凌祐','64','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('169','中日ドラゴンズ','伊藤　準規','65','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('170','中日ドラゴンズ','高橋　聡文','67','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('171','中日ドラゴンズ','小林　正人','69','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('172','中日ドラゴンズ','ダニエル・カブレラ','99','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('173','中日ドラゴンズ','谷繁　元信','27','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('174','中日ドラゴンズ','松井　雅人','38','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('175','中日ドラゴンズ','桂　依央利','40','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('176','中日ドラゴンズ','杉山　翔大','45','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('177','中日ドラゴンズ','武山　真吾','49','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('178','中日ドラゴンズ','小田　幸平','52','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('179','中日ドラゴンズ','田中　大輔','58','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('180','中日ドラゴンズ','赤田　龍一郎','68','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('181','中日ドラゴンズ','アンダーソン・エルナンデス','00','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('182','中日ドラゴンズ','エクトル・ルナ','0','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('183','中日ドラゴンズ','堂上　直倫','1','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('184','中日ドラゴンズ','荒木　雅博','2','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('185','中日ドラゴンズ','吉川　大幾','3','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('186','中日ドラゴンズ','森野　将彦','7','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('187','中日ドラゴンズ','高橋　周平','9','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('188','中日ドラゴンズ','山崎　武司','20','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('189','中日ドラゴンズ','小笠原　道大','36','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('190','中日ドラゴンズ','岩崎　恭平','37','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('191','中日ドラゴンズ','藤澤　拓斗','46','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('192','中日ドラゴンズ','溝脇　隼人','48','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('193','中日ドラゴンズ','中田　亮二','50','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('194','中日ドラゴンズ','森越　祐人','54','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('195','中日ドラゴンズ','福田　永将','55','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('196','中日ドラゴンズ','谷　哲也','70','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('197','中日ドラゴンズ','藤井　淳志','4','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('198','中日ドラゴンズ','和田　一浩','5','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('199','中日ドラゴンズ','平田　良介','6','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('200','中日ドラゴンズ','大島　洋平','8','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('201','中日ドラゴンズ','野本　圭','31','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('202','中日ドラゴンズ','アレクシス・ゴメス','44','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('203','中日ドラゴンズ','松井　佑介','56','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('204','中日ドラゴンズ','井藤　真吾','60','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('205','中日ドラゴンズ','工藤　隆人','62','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('206','中日ドラゴンズ','堂上　剛裕','63','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('207','中日ドラゴンズ','古本　武尊','66','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('208','横浜DeNAベイスターズ','中畑　清','70','監督');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('209','横浜DeNAベイスターズ','藤井　秀悟','00','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('210','横浜DeNAベイスターズ','山口　俊','11','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('211','横浜DeNAベイスターズ','小林　寛','12','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('212','横浜DeNAベイスターズ','柿田　裕太','13','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('213','横浜DeNAベイスターズ','小林　太志','14','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('214','横浜DeNAベイスターズ','井納　翔一','15','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('215','横浜DeNAベイスターズ','加賀　繁','16','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('216','横浜DeNAベイスターズ','三嶋　一輝','17','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('217','横浜DeNAベイスターズ','三浦　大輔','18','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('218','横浜DeNAベイスターズ','藤江　均','19','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('219','横浜DeNAベイスターズ','須田　幸太','20','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('220','横浜DeNAベイスターズ','加賀美　希昇','21','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('221','横浜DeNAベイスターズ','高崎　健太郎','22','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('222','横浜DeNAベイスターズ','林　昌範','24','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('223','横浜DeNAベイスターズ','久保　康友','27','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('224','横浜DeNAベイスターズ','北方　悠誠','28','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('225','横浜DeNAベイスターズ','菊地　和正','30','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('226','横浜DeNAベイスターズ','平田　真吾','34','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('227','横浜DeNAベイスターズ','三上　朋也','35','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('228','横浜DeNAベイスターズ','神内　靖','38','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('229','横浜DeNAベイスターズ','大原　慎司','41','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('230','横浜DeNAベイスターズ','安部　建輝','43','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('231','横浜DeNAベイスターズ','土屋　健二','45','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('232','横浜DeNAベイスターズ','田中　健二朗','46','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('233','横浜DeNAベイスターズ','尚成','47','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('234','横浜DeNAベイスターズ','山下　峻','48','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('235','横浜DeNAベイスターズ','ギジェルモ・モスコーソ','49','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('236','横浜DeNAベイスターズ','ホルヘ・ソーサ','53','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('237','横浜DeNAベイスターズ','小杉　陽太','54','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('238','横浜DeNAベイスターズ','長田　秀一郎','56','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('239','横浜DeNAベイスターズ','大田　阿斗里','58','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('240','横浜DeNAベイスターズ','エンジェルベルト・ソト','61','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('241','横浜DeNAベイスターズ','萬谷　康平','62','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('242','横浜DeNAベイスターズ','眞下　貴之','64','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('243','横浜DeNAベイスターズ','国吉　佑樹','65','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('244','横浜DeNAベイスターズ','伊藤　拓郎','67','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('245','横浜DeNAベイスターズ','冨田　康祐','68','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('246','横浜DeNAベイスターズ','黒羽根　利規','9','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('247','横浜DeNAベイスターズ','高城　俊人','32','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('248','横浜DeNAベイスターズ','嶺井　博希','39','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('249','横浜DeNAベイスターズ','鶴岡　賢二郎','57','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('250','横浜DeNAベイスターズ','西森　将司','66','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('251','横浜DeNAベイスターズ','山崎　憲晴','0','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('252','横浜DeNAベイスターズ','石川　雄洋','7','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('253','横浜DeNAベイスターズ','内村　賢介','23','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('254','横浜DeNAベイスターズ','筒香　嘉智','25','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('255','横浜DeNAベイスターズ','白崎　浩之','29','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('256','横浜DeNAベイスターズ','柳田　殖生','36','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('257','横浜DeNAベイスターズ','飛雄馬','40','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('258','横浜DeNAベイスターズ','トニ・ブランコ','42','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('259','横浜DeNAベイスターズ','渡邊　雄貴','44','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('260','横浜DeNAベイスターズ','宮崎　敏郎','51','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('261','横浜DeNAベイスターズ','アーロム・バルディリス','52','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('262','横浜DeNAベイスターズ','後藤　武敏','55','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('263','横浜DeNAベイスターズ','加藤　政義','60','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('264','横浜DeNAベイスターズ','中村　紀洋','99','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('265','横浜DeNAベイスターズ','金城　龍彦','1','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('266','横浜DeNAベイスターズ','梶谷　隆幸','3','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('267','横浜DeNAベイスターズ','荒波　翔','4','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('268','横浜DeNAベイスターズ','松本　啓二朗','6','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('269','横浜DeNAベイスターズ','多村　仁志','8','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('270','横浜DeNAベイスターズ','井手　正太郎','26','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('271','横浜DeNAベイスターズ','赤堀　大智','31','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('272','横浜DeNAベイスターズ','乙坂　智','33','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('273','横浜DeNAベイスターズ','桑原　将志','37','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('274','横浜DeNAベイスターズ','下園　辰哉','50','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('275','横浜DeNAベイスターズ','関根　大気','63','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('276','東京ヤクルトスワローズ','小川　淳司','80','監督');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('277','東京ヤクルトスワローズ','由規','11','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('278','東京ヤクルトスワローズ','石山　泰稚','12','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('279','東京ヤクルトスワローズ','秋吉　亮','14','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('280','東京ヤクルトスワローズ','村中　恭兵','15','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('281','東京ヤクルトスワローズ','木谷　良平','16','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('282','東京ヤクルトスワローズ','杉浦　稔大','18','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('283','東京ヤクルトスワローズ','石川　雅規','19','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('284','東京ヤクルトスワローズ','山本　哲哉','20','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('285','東京ヤクルトスワローズ','松岡　健一','21','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('286','東京ヤクルトスワローズ','館山　昌平','25','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('287','東京ヤクルトスワローズ','久古　健太郎','26','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('288','東京ヤクルトスワローズ','小川　泰弘','29','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('289','東京ヤクルトスワローズ','トニー・バーネット','34','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('290','東京ヤクルトスワローズ','田川　賢吾','35','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('291','東京ヤクルトスワローズ','クリス・ナーブソン','38','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('292','東京ヤクルトスワローズ','古野　正人','40','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('293','東京ヤクルトスワローズ','七條　祐樹','42','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('294','東京ヤクルトスワローズ','江村　将也','43','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('295','東京ヤクルトスワローズ','岩橋　慶侍','44','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('296','東京ヤクルトスワローズ','日高　亮','45','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('297','東京ヤクルトスワローズ','赤川　克紀','47','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('298','東京ヤクルトスワローズ','大場　達也','49','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('299','東京ヤクルトスワローズ','オーランド・ロマン','53','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('300','東京ヤクルトスワローズ','中澤　雅人','54','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('301','東京ヤクルトスワローズ','クリス・カーペンター','56','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('302','東京ヤクルトスワローズ','阿部　健太','58','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('303','東京ヤクルトスワローズ','児山　祐斗','61','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('304','東京ヤクルトスワローズ','徳山　武陽','62','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('305','東京ヤクルトスワローズ','山本　斉','63','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('306','東京ヤクルトスワローズ','押本　健彦','65','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('307','東京ヤクルトスワローズ','真田　裕貴','66','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('308','東京ヤクルトスワローズ','平井　諒','67','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('309','東京ヤクルトスワローズ','八木　亮祐','70','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('310','東京ヤクルトスワローズ','金伏　ウーゴ','91','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('311','東京ヤクルトスワローズ','相川　亮二','2','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('312','東京ヤクルトスワローズ','田中　雅彦','28','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('313','東京ヤクルトスワローズ','西田　明央','30','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('314','東京ヤクルトスワローズ','新田　玄気','32','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('315','東京ヤクルトスワローズ','星野　雄大','37','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('316','東京ヤクルトスワローズ','藤井　亮太','51','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('317','東京ヤクルトスワローズ','中村　悠平','52','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('318','東京ヤクルトスワローズ','西浦　直亨','3','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('319','東京ヤクルトスワローズ','川端　慎吾','5','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('320','東京ヤクルトスワローズ','田中　浩康','7','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('321','東京ヤクルトスワローズ','武内　晋一','8','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('322','東京ヤクルトスワローズ','森岡　良介','10','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('323','東京ヤクルトスワローズ','川島　慶三','13','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('324','東京ヤクルトスワローズ','山田　哲人','23','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('325','東京ヤクルトスワローズ','荒木　貴裕','24','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('326','東京ヤクルトスワローズ','畠山　和洋','33','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('327','東京ヤクルトスワローズ','又野　知弥','39','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('328','東京ヤクルトスワローズ','谷内　亮太','46','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('329','東京ヤクルトスワローズ','岩村　明憲','48','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('330','東京ヤクルトスワローズ','野口　祥順','55','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('331','東京ヤクルトスワローズ','今浪　隆博','59','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('332','東京ヤクルトスワローズ','三輪　正義','60','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('333','東京ヤクルトスワローズ','比屋根　渉','0','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('334','東京ヤクルトスワローズ','ウラディミール・バレンティン','4','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('335','東京ヤクルトスワローズ','飯原　誉士','9','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('336','東京ヤクルトスワローズ','松元　ユウイチ','31','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('337','東京ヤクルトスワローズ','川上　竜平','36','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('338','東京ヤクルトスワローズ','雄平','41','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('339','東京ヤクルトスワローズ','上田　剛史','50','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('340','東京ヤクルトスワローズ','松井　淳','57','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('341','東京ヤクルトスワローズ','川崎　成晃','64','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('342','東京ヤクルトスワローズ','ラスティングス・ミレッジ','85','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('343','読売ジャイアンツ','原　辰徳','88','監督');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('344','読売ジャイアンツ','久保　裕也','11','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('345','読売ジャイアンツ','香月　良太','13','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('346','読売ジャイアンツ','澤村　拓一','15','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('347','読売ジャイアンツ','大竹　寛','17','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('348','読売ジャイアンツ','杉内　俊哉','18','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('349','読売ジャイアンツ','菅野　智之','19','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('350','読売ジャイアンツ','スコット・マシソン','20','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('351','読売ジャイアンツ','内海　哲也','26','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('352','読売ジャイアンツ','高木　京介','28','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('353','読売ジャイアンツ','福田　聡志','29','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('354','読売ジャイアンツ','宮國　椋丞','30','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('355','読売ジャイアンツ','西村　健太朗','35','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('356','読売ジャイアンツ','田原　誠次','37','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('357','読売ジャイアンツ','松本　竜也','41','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('358','読売ジャイアンツ','青木　高広','43','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('359','読売ジャイアンツ','今村　信貴','45','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('360','読売ジャイアンツ','山口　鉄也','47','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('361','読売ジャイアンツ','クリス・セドン','49','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('362','読売ジャイアンツ','公文　克彦','57','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('363','読売ジャイアンツ','小山　雄輝','59','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('364','読売ジャイアンツ','星野　真澄','60','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('365','読売ジャイアンツ','江柄子　裕樹','62','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('366','読売ジャイアンツ','笠原　将生','63','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('367','読売ジャイアンツ','須永　英輝','66','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('368','読売ジャイアンツ','越智　大祐','67','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('369','読売ジャイアンツ','田中　太一','68','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('370','読売ジャイアンツ','田口　麗斗','90','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('371','読売ジャイアンツ','平良　拳太郎','92','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('372','読売ジャイアンツ','土田　瑞起','93','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('373','読売ジャイアンツ','阿南　徹','99','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('374','読売ジャイアンツ','阿部　慎之助','10','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('375','読売ジャイアンツ','小林　誠司','22','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('376','読売ジャイアンツ','實松　一成','27','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('377','読売ジャイアンツ','井野　卓','38','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('378','読売ジャイアンツ','加藤　健','40','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('379','読売ジャイアンツ','河野　元貴','53','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('380','読売ジャイアンツ','鬼屋敷　正人','64','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('381','読売ジャイアンツ','寺内　崇幸','00','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('382','読売ジャイアンツ','藤村　大介','0','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('383','読売ジャイアンツ','井端　弘和','2','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('384','読売ジャイアンツ','ホセ・ロペス','5','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('385','読売ジャイアンツ','坂本　勇人','6','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('386','読売ジャイアンツ','片岡　治大','8','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('387','読売ジャイアンツ','村田　修一','25','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('388','読売ジャイアンツ','石井　義人','33','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('389','読売ジャイアンツ','中井　大介','36','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('390','読売ジャイアンツ','大累　進','39','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('391','読売ジャイアンツ','坂口　真規','56','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('392','読売ジャイアンツ','立岡　宗一郎','58','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('393','読売ジャイアンツ','和田　恋','61','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('394','読売ジャイアンツ','辻　東倫','65','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('395','読売ジャイアンツ','奥村　展征','91','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('396','読売ジャイアンツ','長野　久義','7','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('397','読売ジャイアンツ','亀井　善行','9','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('398','読売ジャイアンツ','鈴木　尚広','12','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('399','読売ジャイアンツ','フレデリク・セペダ','23','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('400','読売ジャイアンツ','高橋　由伸','24','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('401','読売ジャイアンツ','松本　哲也','31','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('402','読売ジャイアンツ','橋本　到','32','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('403','読売ジャイアンツ','レスリー・アンダーソン','42','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('404','読売ジャイアンツ','大田　泰示','44','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('405','読売ジャイアンツ','矢野　謙次','48','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('406','読売ジャイアンツ','加治前　竜一','50','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('407','読売ジャイアンツ','横川　史学','51','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('408','読売ジャイアンツ','隠善　智也','52','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('409','東北楽天ゴールデンイーグルス','星野　仙一','77','監督');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('410','東北楽天ゴールデンイーグルス','松井　裕樹','1','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('411','東北楽天ゴールデンイーグルス','塩見　貴洋','11','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('412','東北楽天ゴールデンイーグルス','濱矢　廣大','13','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('413','東北楽天ゴールデンイーグルス','則本　昂大','14','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('414','東北楽天ゴールデンイーグルス','トラビス・ブラックリー','15','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('415','東北楽天ゴールデンイーグルス','森　雄大','16','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('416','東北楽天ゴールデンイーグルス','長谷部　康平','17','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('417','東北楽天ゴールデンイーグルス','釜田　佳直','21','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('418','東北楽天ゴールデンイーグルス','戸村　健次','22','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('419','東北楽天ゴールデンイーグルス','高堀　和也','24','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('420','東北楽天ゴールデンイーグルス','金刃　憲人','26','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('421','東北楽天ゴールデンイーグルス','片山　博視','28','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('422','東北楽天ゴールデンイーグルス','永井　怜','30','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('423','東北楽天ゴールデンイーグルス','美馬　学','31','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('424','東北楽天ゴールデンイーグルス','武藤　好貴','34','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('425','東北楽天ゴールデンイーグルス','西宮　悠介','38','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('426','東北楽天ゴールデンイーグルス','ブライアン・ファルケンボーグ','40','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('427','東北楽天ゴールデンイーグルス','青山　浩二','41','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('428','東北楽天ゴールデンイーグルス','斎藤　隆','44','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('429','東北楽天ゴールデンイーグルス','川井　貴志','45','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('430','東北楽天ゴールデンイーグルス','ルーク・ファンミル','46','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('431','東北楽天ゴールデンイーグルス','大塚　尚仁','47','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('432','東北楽天ゴールデンイーグルス','相原　和友','53','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('433','東北楽天ゴールデンイーグルス','横山　貴明','54','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('434','東北楽天ゴールデンイーグルス','小山　伸一郎','57','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('435','東北楽天ゴールデンイーグルス','辛島　航','58','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('436','東北楽天ゴールデンイーグルス','菊池　保則','59','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('437','東北楽天ゴールデンイーグルス','古川　侑利','60','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('438','東北楽天ゴールデンイーグルス','上園　啓史','61','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('439','東北楽天ゴールデンイーグルス','相沢　晋','62','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('440','東北楽天ゴールデンイーグルス','福山　博之','64','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('441','東北楽天ゴールデンイーグルス','宮川　将','90','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('442','東北楽天ゴールデンイーグルス','今野　龍太','99','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('443','東北楽天ゴールデンイーグルス','内田　靖人','8','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('444','東北楽天ゴールデンイーグルス','小関　翔太','29','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('445','東北楽天ゴールデンイーグルス','嶋　基宏','37','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('446','東北楽天ゴールデンイーグルス','下妻　貴寛','39','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('447','東北楽天ゴールデンイーグルス','伊志嶺　忠','48','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('448','東北楽天ゴールデンイーグルス','小山　桂司','65','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('449','東北楽天ゴールデンイーグルス','阿部　俊人','00','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('450','東北楽天ゴールデンイーグルス','三好　匠','2','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('451','東北楽天ゴールデンイーグルス','後藤　光尊','4','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('452','東北楽天ゴールデンイーグルス','藤田　一也','6','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('453','東北楽天ゴールデンイーグルス','松井　稼頭央','7','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('454','東北楽天ゴールデンイーグルス','ケビン・ユーキリス','20','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('455','東北楽天ゴールデンイーグルス','銀次','33','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('456','東北楽天ゴールデンイーグルス','小斉　祐輔','43','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('457','東北楽天ゴールデンイーグルス','西田　哲朗','55','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('458','東北楽天ゴールデンイーグルス','中川　大志','56','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('459','東北楽天ゴールデンイーグルス','西村　弥','66','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('460','東北楽天ゴールデンイーグルス','岩崎　達郎','67','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('461','東北楽天ゴールデンイーグルス','仲澤　広基','68','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('462','東北楽天ゴールデンイーグルス','森山　周','0','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('463','東北楽天ゴールデンイーグルス','牧田　明久','5','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('464','東北楽天ゴールデンイーグルス','聖澤　諒','23','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('465','東北楽天ゴールデンイーグルス','アンドリュー・ジョーンズ','25','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('466','東北楽天ゴールデンイーグルス','岡島　豪郎','27','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('467','東北楽天ゴールデンイーグルス','枡田　慎太郎','32','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('468','東北楽天ゴールデンイーグルス','島内　宏明','35','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('469','東北楽天ゴールデンイーグルス','榎本　葵','36','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('470','東北楽天ゴールデンイーグルス','ジョン・ボウカー','42','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('471','東北楽天ゴールデンイーグルス','島井　寛仁','50','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('472','東北楽天ゴールデンイーグルス','柿澤　貴裕','51','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('473','東北楽天ゴールデンイーグルス','中島　俊哉','52','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('474','東北楽天ゴールデンイーグルス','北川　倫太郎','63','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('475','埼玉西武ライオンズ','伊原　春樹','73','監督');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('476','埼玉西武ライオンズ','岸　孝之','11','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('477','埼玉西武ライオンズ','岩尾　利弘','12','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('478','埼玉西武ライオンズ','西口　文也','13','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('479','埼玉西武ライオンズ','増田　達至','14','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('480','埼玉西武ライオンズ','大石　達也','15','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('481','埼玉西武ライオンズ','菊池　雄星','16','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('482','埼玉西武ライオンズ','豊田　拓矢','19','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('483','埼玉西武ライオンズ','野上　亮磨','20','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('484','埼玉西武ライオンズ','十亀　剣','21','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('485','埼玉西武ライオンズ','岡本　篤志','22','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('486','埼玉西武ライオンズ','平野　将光','23','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('487','埼玉西武ライオンズ','マイケル・ボウデン','26','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('488','埼玉西武ライオンズ','藤原　良平','28','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('489','埼玉西武ライオンズ','小石　博孝','29','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('490','埼玉西武ライオンズ','岡本　洋介','30','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('491','埼玉西武ライオンズ','川崎　雄介','34','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('492','埼玉西武ライオンズ','牧田　和久','35','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('493','埼玉西武ライオンズ','松永　浩典','38','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('494','埼玉西武ライオンズ','中郷　大樹','39','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('495','埼玉西武ライオンズ','山口　嵩之','40','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('496','埼玉西武ライオンズ','グレッグ・レイノルズ','42','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('497','埼玉西武ライオンズ','高橋　朋己','43','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('498','埼玉西武ライオンズ','中崎　雄太','46','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('499','埼玉西武ライオンズ','武隈　祥太','48','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('500','埼玉西武ライオンズ','福倉　健太郎','50','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('501','埼玉西武ライオンズ','ランディ・ウィリアムス','54','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('502','埼玉西武ライオンズ','松下　建太','57','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('503','埼玉西武ライオンズ','佐藤　勇','63','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('504','埼玉西武ライオンズ','田中　靖洋','66','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('505','埼玉西武ライオンズ','宮田　和希','68','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('506','埼玉西武ライオンズ','誠','71','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('507','埼玉西武ライオンズ','森　友哉','10','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('508','埼玉西武ライオンズ','星　孝典','25','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('509','埼玉西武ライオンズ','炭谷　銀仁朗','27','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('510','埼玉西武ライオンズ','岡田　雅利','37','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('511','埼玉西武ライオンズ','上本　達之','49','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('512','埼玉西武ライオンズ','中田　祥多','64','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('513','埼玉西武ライオンズ','藤澤　亨明','78','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('514','埼玉西武ライオンズ','金子　侑司','2','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('515','埼玉西武ライオンズ','鬼崎　裕司','4','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('516','埼玉西武ライオンズ','山崎　浩司','5','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('517','埼玉西武ライオンズ','コーディ・ランサム','6','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('518','埼玉西武ライオンズ','脇谷　亮太','7','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('519','埼玉西武ライオンズ','渡辺　直人','8','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('520','埼玉西武ライオンズ','浅村　栄斗','32','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('521','埼玉西武ライオンズ','山川　穂高','33','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('522','埼玉西武ライオンズ','美沢　将','44','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('523','埼玉西武ライオンズ','林崎　遼','45','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('524','埼玉西武ライオンズ','金子　一輝','56','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('525','埼玉西武ライオンズ','永江　恭平','59','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('526','埼玉西武ライオンズ','中村　剛也','60','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('527','埼玉西武ライオンズ','梅田　尚通','67','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('528','埼玉西武ライオンズ','エルネスト・メヒア','99','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('529','埼玉西武ライオンズ','森本　稀哲','0','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('530','埼玉西武ライオンズ','栗山　巧','1','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('531','埼玉西武ライオンズ','大崎　雄太朗','9','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('532','埼玉西武ライオンズ','坂田　遼','31','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('533','埼玉西武ライオンズ','米野　智人','36','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('534','埼玉西武ライオンズ','木村　文紀','51','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('535','埼玉西武ライオンズ','石川　貢','53','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('536','埼玉西武ライオンズ','秋山　翔吾','55','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('537','埼玉西武ライオンズ','熊代　聖人','58','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('538','埼玉西武ライオンズ','田代　将太郎','61','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('539','埼玉西武ライオンズ','駒月　仁人','62','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('540','埼玉西武ライオンズ','斉藤　彰吾','65','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('541','埼玉西武ライオンズ','アブナー・アブレイユ','72','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('542','千葉ロッテマリーンズ','伊東　勤','83','監督');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('543','千葉ロッテマリーンズ','荻野　忠寛','0','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('544','千葉ロッテマリーンズ','大嶺　祐太','11','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('545','千葉ロッテマリーンズ','石川　歩','12','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('546','千葉ロッテマリーンズ','中後　悠平','13','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('547','千葉ロッテマリーンズ','大谷　智久','14','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('548','千葉ロッテマリーンズ','上野　大樹','15','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('549','千葉ロッテマリーンズ','涌井　秀章','16','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('550','千葉ロッテマリーンズ','成瀬　善久','17','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('551','千葉ロッテマリーンズ','藤岡　貴裕','18','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('552','千葉ロッテマリーンズ','唐川　侑己','19','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('553','千葉ロッテマリーンズ','服部　泰卓','20','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('554','千葉ロッテマリーンズ','内　竜也','21','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('555','千葉ロッテマリーンズ','古谷　拓哉','27','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('556','千葉ロッテマリーンズ','松永　昂大','28','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('557','千葉ロッテマリーンズ','西野　勇士','29','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('558','千葉ロッテマリーンズ','伊藤　義弘','30','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('559','千葉ロッテマリーンズ','南　昌輝','33','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('560','千葉ロッテマリーンズ','木村　優太','34','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('561','千葉ロッテマリーンズ','川満　寛弥','36','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('562','千葉ロッテマリーンズ','吉原　正平','40','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('563','千葉ロッテマリーンズ','小林　敦','41','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('564','千葉ロッテマリーンズ','香月　良仁','42','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('565','千葉ロッテマリーンズ','黒沢　翔太','43','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('566','千葉ロッテマリーンズ','セス・グライシンガー','46','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('567','千葉ロッテマリーンズ','植松　優友','51','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('568','千葉ロッテマリーンズ','益田　直也','52','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('569','千葉ロッテマリーンズ','藤谷　周平','54','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('570','千葉ロッテマリーンズ','阿部　和成','60','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('571','千葉ロッテマリーンズ','二木　康太','64','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('572','千葉ロッテマリーンズ','カルロス・ロサ','99','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('573','千葉ロッテマリーンズ','里崎　智也','22','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('574','千葉ロッテマリーンズ','吉田　裕太','24','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('575','千葉ロッテマリーンズ','金澤　岳','25','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('576','千葉ロッテマリーンズ','川本　良平','39','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('577','千葉ロッテマリーンズ','田村　龍弘','45','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('578','千葉ロッテマリーンズ','江村　直也','53','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('579','千葉ロッテマリーンズ','小池　翔大','57','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('580','千葉ロッテマリーンズ','高濱　卓也','00','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('581','千葉ロッテマリーンズ','根元　俊一','2','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('582','千葉ロッテマリーンズ','井口　資仁','6','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('583','千葉ロッテマリーンズ','鈴木　大地','7','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('584','千葉ロッテマリーンズ','今江　敏晃','8','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('585','千葉ロッテマリーンズ','福浦　和也','9','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('586','千葉ロッテマリーンズ','大松　尚逸','10','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('587','千葉ロッテマリーンズ','塀内　久雄','23','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('588','千葉ロッテマリーンズ','クレイグ・ブラゼル','32','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('589','千葉ロッテマリーンズ','三木　亮','37','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('590','千葉ロッテマリーンズ','井上　晴哉','44','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('591','千葉ロッテマリーンズ','ルイス・クルーズ','47','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('592','千葉ロッテマリーンズ','大嶺　翔太','50','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('593','千葉ロッテマリーンズ','細谷　圭','59','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('594','千葉ロッテマリーンズ','青松　敬鎔','63','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('595','千葉ロッテマリーンズ','早坂　圭介','68','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('596','千葉ロッテマリーンズ','角　晃多','69','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('597','千葉ロッテマリーンズ','清田　育宏','1','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('598','千葉ロッテマリーンズ','サブロー','3','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('599','千葉ロッテマリーンズ','荻野　貴司','4','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('600','千葉ロッテマリーンズ','伊志嶺　翔大','5','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('601','千葉ロッテマリーンズ','Ｇ．Ｇ．佐藤','48','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('602','千葉ロッテマリーンズ','神戸　拓光','55','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('603','千葉ロッテマリーンズ','チャッド・ハフマン','56','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('604','千葉ロッテマリーンズ','角中　勝也','61','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('605','千葉ロッテマリーンズ','加藤　翔平','65','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('606','千葉ロッテマリーンズ','岡田　幸文','66','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('607','福岡ソフトバンクホークス','秋山　幸二','81','監督');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('608','福岡ソフトバンクホークス','江尻　慎太郎','00','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('609','福岡ソフトバンクホークス','中田　賢一','11','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('610','福岡ソフトバンクホークス','二保　旭','13','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('611','福岡ソフトバンクホークス','加治屋　蓮','14','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('612','福岡ソフトバンクホークス','東浜　巨','16','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('613','福岡ソフトバンクホークス','ブライアン・ウルフ','17','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('614','福岡ソフトバンクホークス','新垣　渚','18','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('615','福岡ソフトバンクホークス','森福　允彦','19','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('616','福岡ソフトバンクホークス','寺原　隼人','20','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('617','福岡ソフトバンクホークス','岩嵜　翔','21','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('618','福岡ソフトバンクホークス','巽　真悟','25','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('619','福岡ソフトバンクホークス','川原　弘之','26','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('620','福岡ソフトバンクホークス','大隣　憲司','28','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('621','福岡ソフトバンクホークス','大場　翔太','29','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('622','福岡ソフトバンクホークス','武田　翔太','30','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('623','福岡ソフトバンクホークス','吉本　祥二','33','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('624','福岡ソフトバンクホークス','山田　大樹','34','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('625','福岡ソフトバンクホークス','岡島　秀樹','37','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('626','福岡ソフトバンクホークス','森　唯斗','38','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('627','福岡ソフトバンクホークス','山中　浩史','39','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('628','福岡ソフトバンクホークス','千賀　滉大','41','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('629','福岡ソフトバンクホークス','飯田　優也','42','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('630','福岡ソフトバンクホークス','帆足　和幸','47','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('631','福岡ソフトバンクホークス','岡本　健','48','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('632','福岡ソフトバンクホークス','伊藤　祐介','49','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('633','福岡ソフトバンクホークス','攝津　正','50','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('634','福岡ソフトバンクホークス','五十嵐　亮太','53','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('635','福岡ソフトバンクホークス','柳瀬　明宏','54','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('636','福岡ソフトバンクホークス','ジェイソン・スタンリッジ','55','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('637','福岡ソフトバンクホークス','星野　大地','56','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('638','福岡ソフトバンクホークス','嘉弥真　新也','57','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('639','福岡ソフトバンクホークス','デニス・サファテ','58','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('640','福岡ソフトバンクホークス','ポール・オセゲラ','59','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('641','福岡ソフトバンクホークス','金　無英','61','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('642','福岡ソフトバンクホークス','笠原　大芽','63','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('643','福岡ソフトバンクホークス','エディソン・バリオス','67','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('644','福岡ソフトバンクホークス','鶴岡　慎也','8','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('645','福岡ソフトバンクホークス','高谷　裕亮','12','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('646','福岡ソフトバンクホークス','山下　斐紹','22','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('647','福岡ソフトバンクホークス','細川　亨','27','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('648','福岡ソフトバンクホークス','拓也','62','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('649','福岡ソフトバンクホークス','猪本　健太郎','68','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('650','福岡ソフトバンクホークス','高田　知季','0','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('651','福岡ソフトバンクホークス','今宮　健太','2','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('652','福岡ソフトバンクホークス','松中　信彦','3','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('653','福岡ソフトバンクホークス','金子　圭輔','4','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('654','福岡ソフトバンクホークス','松田　宣浩','5','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('655','福岡ソフトバンクホークス','李　大浩','10','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('656','福岡ソフトバンクホークス','塚田　正義','32','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('657','福岡ソフトバンクホークス','明石　健志','36','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('658','福岡ソフトバンクホークス','李　杜軒','45','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('659','福岡ソフトバンクホークス','本多　雄一','46','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('660','福岡ソフトバンクホークス','上林　誠知','51','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('661','福岡ソフトバンクホークス','白根　尚貴','65','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('662','福岡ソフトバンクホークス','牧原　大成','69','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('663','福岡ソフトバンクホークス','バーバロ・カニザレス','95','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('664','福岡ソフトバンクホークス','内川　聖一','1','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('665','福岡ソフトバンクホークス','吉村　裕基','6','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('666','福岡ソフトバンクホークス','城所　龍磨','23','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('667','福岡ソフトバンクホークス','長谷川　勇也','24','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('668','福岡ソフトバンクホークス','福田　秀平','31','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('669','福岡ソフトバンクホークス','江川　智晃','43','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('670','福岡ソフトバンクホークス','柳田　悠岐','44','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('671','福岡ソフトバンクホークス','中村　晃','60','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('672','福岡ソフトバンクホークス','真砂　勇介','64','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('673','オリックス・バファローズ','森脇　浩司','88','監督');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('674','オリックス・バファローズ','松葉　貴大','11','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('675','オリックス・バファローズ','桑原　謙太朗','13','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('676','オリックス・バファローズ','吉田　一将','14','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('677','オリックス・バファローズ','佐藤　達也','15','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('678','オリックス・バファローズ','平野　佳寿','16','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('679','オリックス・バファローズ','東野　峻','17','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('680','オリックス・バファローズ','岸田　護','18','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('681','オリックス・バファローズ','金子　千尋','19','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('682','オリックス・バファローズ','馬原　孝浩','20','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('683','オリックス・バファローズ','西　勇輝','21','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('684','オリックス・バファローズ','東明　大貴','26','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('685','オリックス・バファローズ','八木　智哉','27','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('686','オリックス・バファローズ','小松　聖','28','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('687','オリックス・バファローズ','井川　慶','29','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('688','オリックス・バファローズ','佐藤　峻一','31','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('689','オリックス・バファローズ','ブランドン・ディクソン','32','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('690','オリックス・バファローズ','中山　慎也','34','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('691','オリックス・バファローズ','比嘉　幹貴','35','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('692','オリックス・バファローズ','平井　正史','36','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('693','オリックス・バファローズ','大山　暁史','40','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('694','オリックス・バファローズ','伊原　正樹','43','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('695','オリックス・バファローズ','海田　智行','47','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('696','オリックス・バファローズ','甲藤　啓介','48','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('697','オリックス・バファローズ','近藤　一樹','50','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('698','オリックス・バファローズ','山田　修義','57','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('699','オリックス・バファローズ','戸田　亮','58','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('700','オリックス・バファローズ','塚原　頌平','59','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('701','オリックス・バファローズ','前田　祐二','60','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('702','オリックス・バファローズ','森本　将太','64','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('703','オリックス・バファローズ','山崎　正貴','65','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('704','オリックス・バファローズ','古川　秀一','67','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('705','オリックス・バファローズ','柴田　健斗','69','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('706','オリックス・バファローズ','アレッサンドロ・マエストリ','91','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('707','オリックス・バファローズ','伊藤　光','22','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('708','オリックス・バファローズ','伏見　寅威','23','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('709','オリックス・バファローズ','若月　健矢','37','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('710','オリックス・バファローズ','齋藤　俊雄','45','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('711','オリックス・バファローズ','庄司　龍二','49','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('712','オリックス・バファローズ','山崎　勝己','62','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('713','オリックス・バファローズ','ユニエスキー・ベタンコート','1','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('714','オリックス・バファローズ','原　拓也','2','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('715','オリックス・バファローズ','安達　了一','3','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('716','オリックス・バファローズ','エステバン・ヘルマン','4','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('717','オリックス・バファローズ','平野　恵一','5','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('718','オリックス・バファローズ','高橋　信二','6','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('719','オリックス・バファローズ','三ツ俣　大樹','30','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('720','オリックス・バファローズ','縞田　拓弥','33','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('721','オリックス・バファローズ','小島　脩平','38','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('722','オリックス・バファローズ','園部　聡','44','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('723','オリックス・バファローズ','堤　裕貴','54','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('724','オリックス・バファローズ','奥浪　鏡','61','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('725','オリックス・バファローズ','山本　和作','66','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('726','オリックス・バファローズ','丸毛　謙一','00','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('727','オリックス・バファローズ','鉄平','0','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('728','オリックス・バファローズ','糸井　嘉男','7','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('729','オリックス・バファローズ','駿太','8','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('730','オリックス・バファローズ','坂口　智隆','9','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('731','オリックス・バファローズ','谷　佳知','10','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('732','オリックス・バファローズ','宮崎　祐樹','24','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('733','オリックス・バファローズ','竹原　直隆','25','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('734','オリックス・バファローズ','ウィリー・モー・ペーニャ','42','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('735','オリックス・バファローズ','川端　崇義','46','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('736','オリックス・バファローズ','吉田　雄人','53','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('737','オリックス・バファローズ','Ｔ－岡田','55','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('738','オリックス・バファローズ','武田　健吾','56','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('739','オリックス・バファローズ','中村　一生','63','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('740','オリックス・バファローズ','深江　真登','68','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('741','オリックス・バファローズ','西川　拓喜','99','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('742','北海道日本ハムファイターズ','栗山　英樹','80','監督');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('743','北海道日本ハムファイターズ','大谷　翔平','11','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('744','北海道日本ハムファイターズ','石井　裕也','13','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('745','北海道日本ハムファイターズ','大塚　豊','14','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('746','北海道日本ハムファイターズ','ルイス・メンドーサ','15','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('747','北海道日本ハムファイターズ','乾　真大','16','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('748','北海道日本ハムファイターズ','浦野　博司','17','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('749','北海道日本ハムファイターズ','斎藤　佑樹','18','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('750','北海道日本ハムファイターズ','増井　浩俊','19','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('751','北海道日本ハムファイターズ','マイケル・クロッタ','20','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('752','北海道日本ハムファイターズ','武田　久','21','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('753','北海道日本ハムファイターズ','藤岡　好明','22','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('754','北海道日本ハムファイターズ','宮西　尚生','25','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('755','北海道日本ハムファイターズ','新垣　勇人','28','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('756','北海道日本ハムファイターズ','木佐貫　洋','29','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('757','北海道日本ハムファイターズ','鍵谷　陽平','30','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('758','北海道日本ハムファイターズ','根本　朋久','32','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('759','北海道日本ハムファイターズ','矢貫　俊之','33','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('760','北海道日本ハムファイターズ','吉川　光夫','34','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('761','北海道日本ハムファイターズ','榎下　陽大','35','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('762','北海道日本ハムファイターズ','中村　勝','36','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('763','北海道日本ハムファイターズ','武田　勝','38','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('764','北海道日本ハムファイターズ','高梨　裕稔','39','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('765','北海道日本ハムファイターズ','金平　将至','40','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('766','北海道日本ハムファイターズ','白村　明弘','43','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('767','北海道日本ハムファイターズ','増渕　竜義','45','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('768','北海道日本ハムファイターズ','森内　壽春','47','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('769','北海道日本ハムファイターズ','谷元　圭介','48','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('770','北海道日本ハムファイターズ','運天　ジョン・クレイトン','55','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('771','北海道日本ハムファイターズ','屋宜　照悟','57','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('772','北海道日本ハムファイターズ','齊藤　勝','58','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('773','北海道日本ハムファイターズ','河野　秀数','59','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('774','北海道日本ハムファイターズ','佐藤　祥万','62','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('775','北海道日本ハムファイターズ','上沢　直之','63','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('776','北海道日本ハムファイターズ','多田野　数人','65','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('777','北海道日本ハムファイターズ','アンソニー・カーター','70','投手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('778','北海道日本ハムファイターズ','大野　奨太','2','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('779','北海道日本ハムファイターズ','中嶋　聡','27','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('780','北海道日本ハムファイターズ','尾崎　匡哉','53','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('781','北海道日本ハムファイターズ','近藤　健介','54','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('782','北海道日本ハムファイターズ','市川　友也','56','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('783','北海道日本ハムファイターズ','荒張　裕司','60','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('784','北海道日本ハムファイターズ','大嶋　匠','66','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('785','北海道日本ハムファイターズ','石川　亮','68','捕手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('786','北海道日本ハムファイターズ','飯山　裕志','4','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('787','北海道日本ハムファイターズ','小谷野　栄一','5','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('788','北海道日本ハムファイターズ','中田　翔','6','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('789','北海道日本ハムファイターズ','大引　啓次','7','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('790','北海道日本ハムファイターズ','金子　誠','8','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('791','北海道日本ハムファイターズ','中島　卓也','9','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('792','北海道日本ハムファイターズ','松本　剛','12','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('793','北海道日本ハムファイターズ','渡邉　諒','23','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('794','北海道日本ハムファイターズ','森本　龍弥','24','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('795','北海道日本ハムファイターズ','西川　遥輝','26','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('796','北海道日本ハムファイターズ','岡　大海','31','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('797','北海道日本ハムファイターズ','稲葉　篤紀','41','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('798','北海道日本ハムファイターズ','ミチェル・アブレイユ','42','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('799','北海道日本ハムファイターズ','ホアン・ミランダ','46','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('800','北海道日本ハムファイターズ','宇佐美　塁大','50','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('801','北海道日本ハムファイターズ','杉谷　拳士','61','内野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('802','北海道日本ハムファイターズ','陽　岱鋼','1','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('803','北海道日本ハムファイターズ','赤田　将吾','10','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('804','北海道日本ハムファイターズ','北　篤','37','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('805','北海道日本ハムファイターズ','鵜久森　淳志','44','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('806','北海道日本ハムファイターズ','石川　慎吾','49','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('807','北海道日本ハムファイターズ','村田　和哉','51','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('808','北海道日本ハムファイターズ','佐藤　賢治','52','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('809','北海道日本ハムファイターズ','谷口　雄也','64','外野手');
INSERT INTO [player] ([_id],[pgroup],[name],[pnumber],[position]) VALUES ('810','北海道日本ハムファイターズ','岸里　亮佑','67','外野手');
COMMIT;
